### ISSUE TITLE
How to initialize bench with the v14.0.0-beta.4 version ??

### ISSUE THREAD

**Issue by SaberChacha** [frappe/bench#1318] opened 2022-06-05 22:04 UTC
I tried to use the command bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench but the following Error occured :
bench.exceptions.InvalidRemoteException: Invalid version-14 for the remote https://github.com/frappe/frappe.git

**Comment by gavindsouza** [comment] 2022-06-21 06:48
Duplicate of #1317

**Closed as not planned by gavindsouza** 2022-06-21 06:48 UTC
Labels: bug
