### ISSUE TITLE
bench backup fails

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/bench#1236] opened 2021-12-11 11:27 UTC
**Describe the bug** :chart_with_downwards_trend:
bench --verbose --site all backup
fails with
Error: No such option: --site

bench --site all backup
works as expected.

In cron job we've this command. So automatic backups are failing.
0 */6 * * * cd /home/frappe/frappe-bench && /usr/local/bin/bench --verbose --site all backup >> /home/frappe/frappe-bench/logs/backup>

I can see that backups are created until 2 days ago. We've updated the bench via this command in the bench folder 2 days ago.
pip3 install --upgrade frappe-bench

**To Reproduce** :page_with_curl:
1. Issue
bench --verbose --site all backup
or 
/usr/local/bin/bench --verbose --site all backup

**Expected behavior** :chart_with_upwards_trend:
Backup for Site logedo.com has been successfully completed

**OS (please complete the following information):** :cyclone:
Ubuntu 20.04.3 LTS

**Version Information**
Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.7.0
- Frappe Version: 13.16.0
- ERPNext Version: 13.16.1

**Comment by ankush** [comment] 2021-12-11 11:44
does this work if you remove `--verbose` flag...?

**Comment by TurkerTunali** [comment] 2021-12-11 18:55
Yes it works.

**Comment by ankush** [comment] 2021-12-17 13:14
duplicate of https://github.com/frappe/bench/issues/1223

**Closed as completed by ankush** 2021-12-17 13:14 UTC
Labels: bug
