### ISSUE TITLE
error while running this command ...for creating new site --sudo python install.py --develop

### ISSUE THREAD

**Issue by ashinsukumaran** [frappe/bench#748] opened 2018-11-17 06:52 UTC
TASK [bench : Create a new site] ***********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "new-site", "site1.local", "--admin-password", "amma", "--mariadb-root-password", "amma"], "delta": "0:00:12.911740", "end": "2018-11-17 11:53:32.613920", "msg": "non-zero return code", "rc": 1, "start": "2018-11-17 11:53:19.702180", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>\n    main()\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py\", line 33, in new_site\n    db_type = db_type)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py\", line 66, in _new_site\n    source_sql=source_sql,force=force, reinstall=reinstall, db_type=db_type)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/installer.py\", line 40, in install_db\n    remove_missing_apps()\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/installer.py\", line 289, in remove_missing_apps\n    installed_apps = json.loads(frappe.db.get_global(\"installed_apps\") or \"[]\")\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 683, in get_global\n    return self.get_default(key, user)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 687, in get_default\n    d = self.get_defaults(key, parent)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 705, in get_defaults\n    defaults = frappe.defaults.get_defaults(parent)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py\", line 71, in get_defaults\n    globald = get_defaults_for()\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py\", line 193, in get_defaults_for\n    defaults = frappe.cache().hget(\"defaults\", parent)\n  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 165, in hget\n    value = super(redis.Redis, self).hget(_name, key)\nAttributeError: 'super' object has no attribute 'hget'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main", "    \"__main__\", mod_spec)", "  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code", "    exec(code, run_globals)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>", "    main()", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main", "    click.Group(commands=commands)(prog_name='bench')", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 764, in __call__", "    return self.main(*args, **kwargs)", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 717, in main", "    rv = self.invoke(ctx)", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 956, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 555, in invoke", "    return callback(*args, **kwargs)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py\", line 33, in new_site", "    db_type = db_type)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py\", line 66, in _new_site", "    source_sql=source_sql,force=force, reinstall=reinstall, db_type=db_type)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/installer.py\", line 40, in install_db", "    remove_missing_apps()", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/installer.py\", line 289, in remove_missing_apps", "    installed_apps = json.loads(frappe.db.get_global(\"installed_apps\") or \"[]\")", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 683, in get_global", "    return self.get_default(key, user)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 687, in get_default", "    d = self.get_defaults(key, parent)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py\", line 705, in get_defaults", "    defaults = frappe.defaults.get_defaults(parent)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py\", line 71, in get_defaults", "    globald = get_defaults_for()", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py\", line 193, in get_defaults_for", "    defaults = frappe.cache().hget(\"defaults\", parent)", "  File \"/home/ashin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py\", line 165, in hget", "    value = super(redis.Redis, self).hget(_name, key)", "AttributeError: 'super' object has no attribute 'hget'"], "stdout": "Creating Database...", "stdout_lines": ["Creating Database..."]}

help me guyz thanks in advance..

**Comment by Thunderbottom** [comment] 2018-11-17 15:50
yes, this issue with the redis update which has temporarily been fixed in the frappe repository commit [`ca59cd`](https://github.com/frappe/frappe/commit/ca59cdc3732f7f9529c28382debbff4baf26ba92). You just need to pull the latest develop branch changes and then try creating a new site again.

basically, from your frappe-bench root, just run:

```sh
$ bench update --pull
```

and then you should be able to create the new site.

**Comment by ashinsukumaran** [comment] 2018-11-18 04:18
> yes, this issue with the redis update which has temporarily been fixed in the frappe repository commit [`ca59cd`](https://github.com/frappe/frappe/commit/ca59cdc3732f7f9529c28382debbff4baf26ba92). You just need to pull the latest develop branch changes and then try creating a new site again.
> 
> basically, from your frappe-bench root, just run:
> 
> ```shell
> $ bench update --pull
> ```
> 
> and then you should be able to create the new site.

it didnt woked for me..nw got error like this.
bench new-site meetiing.dev
MySQL root password: 
Creating Database...
9.24KiB 0:00:00 [ 140MiB/s] [================================>] 100%            
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py", line 33, in new_site
    db_type = db_type)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py", line 66, in _new_site
    source_sql=source_sql,force=force, reinstall=reinstall, db_type=db_type)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/installer.py", line 40, in install_db
    remove_missing_apps()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/installer.py", line 289, in remove_missing_apps
    installed_apps = json.loads(frappe.db.get_global("installed_apps") or "[]")
  File "/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py", line 683, in get_global
    return self.get_default(key, user)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py", line 687, in get_default
    d = self.get_defaults(key, parent)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py", line 705, in get_defaults
    defaults = frappe.defaults.get_defaults(parent)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py", line 71, in get_defaults
    globald = get_defaults_for()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/defaults.py", line 193, in get_defaults_for
    defaults = frappe.cache().hget("defaults", parent)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 165, in hget
    value = super(redis.Redis, self).hget(_name, key)
AttributeError: 'super' object has no attribute 'hget'

**Comment by ashinsukumaran** [comment] 2018-11-19 05:31
> That is the same error as before. Can you go inside `frappe-bench/apps/frappe` and show me the output of the following:
> 
> ```shell
> $ git branch -vv
> $ git pull
> ```

hello , 
this is the output i got .
ashin@ashin-VirtualBox:~/frappe-bench/apps/frappe$ git branch -vv
* develop 92f0a05 [upstream/develop] Merge branch 'staging' into develop
ashin@ashin-VirtualBox:~/frappe-bench/apps/frappe$ git pull
Already up-to-date.
ashin@ashin-VirtualBox:~/frappe-bench/apps/frappe$ 

thank you.
:)

**Comment by Thunderbottom** [comment] 2018-11-19 07:58
okay I think I got what the problem is. Go to the root of your frappe-bench directory and run:

```sh
$ env/bin/pip install redis==2.10.6
```

Then setting up your site shouldn't be an issue. This is because as I said, the redis package for python has recently been updated to `3.0.0`, which breaks some of our code. Pinning the redis version to `2.10.6` should fix it

**Comment by ashinsukumaran** [comment] 2018-11-20 05:58
> okay I think I got what the problem is. Go to the root of your frappe-bench directory and run:
> 
> ```shell
> $ env/bin/pip install redis==2.10.6
> ```
> 
> Then setting up your site shouldn't be an issue. This is because as I said, the redis package for python has recently been updated to `3.0.0`, which breaks some of our code. Pinning the redis version to `2.10.6` should fix it

**Comment by ashinsukumaran** [comment] 2018-11-20 06:02
> okay I think I got what the problem is. Go to the root of your frappe-bench directory and run:
> 
> ```shell
> $ env/bin/pip install redis==2.10.6
> ```
> 
> Then setting up your site shouldn't be an issue. This is because as I said, the redis package for python has recently been updated to `3.0.0`, which breaks some of our code. Pinning the redis version to `2.10.6` should fix it
now got this error.



ashin@ashin-VirtualBox:~/frappe-bench$ bench --site library install-app library_management

Installing library_management...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py", line 166, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/installer.py", line 75, in install_app
    frappe.only_for("System Manager")
  File "/home/ashin/frappe-bench/apps/frappe/frappe/__init__.py", line 508, in only_for
    myroles = set(get_roles())
  File "/home/ashin/frappe-bench/apps/frappe/frappe/__init__.py", line 388, in get_roles
    return get_user().get_roles()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/user.py", line 61, in get_roles
    self.roles = get_roles(self.name)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/permissions.py", line 310, in get_roles
    roles = frappe.cache().hget("roles", user, get)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 173, in hget
    value = generator()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/permissions.py", line 305, in get
    return [r[0] for r in frappe.db.sql("select name from `tabRole`")] # return all available roles
  File "/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py", line 165, in sql
    self._cursor.execute(query)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_00299a408dc3498a.tabRole' doesn't exist")

**Comment by Thunderbottom** [comment] 2018-11-20 08:04
This issue is unrelated to the issue you had before. I suggest you to take a look at our [forums](discuss.erpnext.com) for a solution to this problem.

**Comment by ashinsukumaran** [comment] 2018-11-20 08:30
> okay I think I got what the problem is. Go to the root of your frappe-bench directory and run:
> 
> ```shell
> $ env/bin/pip install redis==2.10.6
> ```
> 
> Then setting up your site shouldn't be an issue. This is because as I said, the redis package for python has recently been updated to `3.0.0`, which breaks some of our code. Pinning the redis version to `2.10.6` should fix it
now got this error.



ashin@ashin-VirtualBox:~/frappe-bench$ bench --site library install-app library_management

Installing library_management...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/commands/site.py", line 166, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/installer.py", line 75, in install_app
    frappe.only_for("System Manager")
  File "/home/ashin/frappe-bench/apps/frappe/frappe/__init__.py", line 508, in only_for
    myroles = set(get_roles())
  File "/home/ashin/frappe-bench/apps/frappe/frappe/__init__.py", line 388, in get_roles
    return get_user().get_roles()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/user.py", line 61, in get_roles
    self.roles = get_roles(self.name)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/permissions.py", line 310, in get_roles
    roles = frappe.cache().hget("roles", user, get)
  File "/home/ashin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 173, in hget
    value = generator()
  File "/home/ashin/frappe-bench/apps/frappe/frappe/permissions.py", line 305, in get
    return [r[0] for r in frappe.db.sql("select name from `tabRole`")] # return all available roles
  File "/home/ashin/frappe-bench/apps/frappe/frappe/database/database.py", line 165, in sql
    self._cursor.execute(query)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ashin/frappe-bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_00299a408dc3498a.tabRole' doesn't exist")

**Comment by ashinsukumaran** [comment] 2018-11-20 08:31
> This issue is unrelated to the issue you had before. I suggest you to take a look at our [forums](discuss.erpnext.com) for a solution to this problem.

thank you

**Closed** 2018-11-20 09:52 UTC
